apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: haneesh-cloud
  region: us-west-1
  version: "1.29"

managedNodeGroups:
  - name: haneesh-nodes
    instanceType: t2.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    volumeSize: 20                
    labels:
      role: worker
    tags:
      nodegroup-role: worker